import type { NextPage } from 'next'
import Head from 'next/head'
import Banner from './components/Banner/Banner';
import SearchForm from './components/SearchForm/SearchForm';
import React,{ useState } from 'react';
import Images from './components/Images/Images';
import InfiniteScroll from "react-infinite-scroll-component";
import searchImages from '../utils/searchImage';

const fetchNextImages = ({page,setImages,setPage,setHasMore}) => async() => {
   const images = await searchImages({
    setPage,
    page,
    setHasMore
   })

   setImages(prevImg => prevImg.concat(images));
}



const Home: NextPage = () => {

  const [images,setImages] = useState([]);
  const [hasMore,setHasMore] = useState(false);
  const [page, setPage] = useState(1);

  const searchFormProps = {
    setImages,
    setPage,
    setHasMore,
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Banner>
        <SearchForm {...searchFormProps}/>
        <InfiniteScroll dataLength={images.length} hasMore={hasMore} next={fetchNextImages({ page, setImages, setPage, setHasMore })}>
          <Images images={images}/>
        </InfiniteScroll>
      </Banner>
    </>
  )
}


export default Home
